---

- name: Running npm install Dependencies
  become: yes
  shell: "npm install {{item}}@latest --save"
  with_items:
  - mongoose
  - body-parser
  - express-method-override
  - express
  args:
    chdir: /vagrant

- name: Running npm install Dev Dependencies
  become: yes
  shell: "npm install -g npm-install-peers --save-dev"
  with_items:
  - \@angular/cli@^1.5.2
  - \@angular/compiler@^4.4.6
  - \@angular/compiler-cli@^4.4.6
  - rxjs@^5.5.2
  - typescript@^2.5.3
  args:
    chdir: /vagrant


- name: Running npm install Dependencies
  become: yes
  shell: "npm install -g npm-install-peers --save"
  args:
    chdir: /vagrant


- name: Running npm install Dev Dependencies
  become: yes
  shell: "npm install -g npm-install-peers --save-dev"
  args:
    chdir: /vagrant
