---

- name: dependency check
  become: yes
  shell: "npm install dependency-check --save"
  args:
    chdir: /vagrant

- name: dev dependency check
  become: yes
  shell: "npm install dependency-check --save-dev"
  args:
    chdir: /vagrant


- name: Running npm install peer Dependencies
  become: yes
  shell: "npm install -g npm-install-peers"
  args:
    chdir: /vagrant

- name: Running npm install Dependencies
  become: yes
  shell: "npm install {{item}}@latest --save-exact --save"
  with_items:
  - mongoose
  - body-parser
  - express-method-override
  - express
  - bcrypt-nodejs
  args:
    chdir: /vagrant

- name: Running npm install Dev Dependencies
  become: yes
  shell: "npm install {{item}} --save-dev"
  with_items:
  - \@angular/cli@^1.*
  - \@angular/core@^4.*
  - \@angular/compiler@^4.*
  - \@angular/compiler-cli@^4.*
  - \@angular/core@4.*
  - rxjs@^5.*
  - typescript@^2.*
  - zone.js@^0.*
  args:
    chdir: /vagrant


- name: Running npm install peer Dev Dependencies
  become: yes
  shell: "npm install npm-install-peers --save-dev"
  args:
    chdir: /vagrant

- name: Check whether client angular side folder exists
  stat:
    path: /vagrant/client
  register: clientfolder_result

- name: Install angular2-flash-message and jwt web tokent for client on angular side
  become: yes
  shell: "npm install {{item}}@latest --save"
  args:
    chdir: /vagrant/client
  when: clientfolder_result.stat.exists == true
  with_items:
    - angular2-flash-messages
    - angular2-jwt


